spring:
  data:
    elasticsearch:
      cluster-name: ${dolphin.elasticsearch.cluster-name}
      cluster-nodes: ${dolphin.elasticsearch.cluster-nodes}

dolphin:
  indices:
    show: sys-log-*, mysql-slowlog-*, sys_user, point-log-*
  swagger:
    enabled: true
    title: 搜索中心
    description: 搜索中心接口文档
    version: 1.0
    base-package: com.dolphin.search.server.controller