spring:
  datasource:
    url: jdbc:mysql://${dolphin.datasource.ip}:3306/user-center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: ${dolphin.datasource.username}
    password: ${dolphin.datasource.password}
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.dolphin.common.model
  global-config:
    db-config:
      id-type: auto

dolphin:
  swagger:
    enabled: true
    title: 用户中心
    description: 用户中心接口文档
    version: 1.0
    base-package: com.dolphin.user.controller
  cache-manager:
    configs:
      - key: menu
        second: 300
      - key: user
        second: 1800
  #多租户配置
  tenant:
    enable: true
    ignoreTables:
      - sys_user
      - sys_role_user
      - sys_role_menu